### ISSUE TITLE
recipe guesses incorrect volume name

### ISSUE THREAD

**Issue by dtenenba** [chef-cookbooks/dmg#33]
### Cookbook version
2.4.0

### Chef-client version
Chef: 12.10.24

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Mac OS X 10.9.5 (test kitchen)

### Scenario:
install Xquartz from a DMG in in a recipe under Test Kitchen

### Steps to Reproduce:
```
include_recipe 'dmg'

dmg_package "Xquartz" do
  source "https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.9.dmg"
  dmg_name "XQuartz-2.7.9"
end

```
### Expected Result:
Xquartz is installed

### Actual Result:
```
             ================================================================================
             Error executing action `run` on resource 'execute[rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications']'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '23'
             ---- Begin output of rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' ----
             STDOUT:
             STDERR: rsync: link_stat "/Volumes/Xquartz/Xquartz.app" failed: No such file or directory (2)
             rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
             ---- End output of rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' ----
             Ran rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' returned 23

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/dmg/providers/package.rb

       64:       execute "rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/#{volumes_dir}/#{new_resource.app}.app' '#{new_resource.destination}'" do
       65:         user new_resource.owner if new_resource.owner
       66:       end
       67:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/dmg/providers/package.rb:64:in `block in class_from_file'

             execute("rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications'") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications'"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "BBS-provision-cookbook-mac"
             end

             Platform:
             ---------
             x86_64-darwin13.0


           ================================================================================
           Error executing action `install` on resource 'dmg_package[Xquartz]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications'] (/tmp/kitchen/cache/cookbooks/dmg/providers/package.rb line 64) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '23'
           ---- Begin output of rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' ----
           STDOUT:
           STDERR: rsync: link_stat "/Volumes/Xquartz/Xquartz.app" failed: No such file or directory (2)
           rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
           ---- End output of rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' ----
           Ran rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Xquartz/Xquartz.app' '/Applications' returned 23

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/BBS-provision-cookbook-mac/recipes/default.rb

           157: dmg_package "Xquartz" do
           158:   source node['xquartz_url']
           159:   dmg_name node['xquartz_name']
           160: end
           161:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/BBS-provision-cookbook-mac/recipes/default.rb:157:in `from_file'

           dmg_package("Xquartz") do
             action :install
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :dmg_package
             cookbook_name "BBS-provision-cookbook-mac"
             recipe_name "default"
             source "https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.9.dmg"
             dmg_name "XQuartz-2.7.9"
             app "Xquartz"
             destination "/Applications"
             type "app"
           end

           Platform:
           ---------
           x86_64-darwin13.0
```

Looks like it is expecting the DMG to be mounted at /Volumes/Xquartz but it's actually mounted at /Volumes/XQuartz-2.7.9.

**Comment by dtenenba** [comment]
Sorry, my bad for not RTFMing. I added `type` and `volumes_dir` parameters.
